---
- name: Create MCH operand
  k8s:
    state: present
    template: "03_MultiClusterHub.yaml.j2"
    wait: true

- name: Check MultiClusterHub (MCH) deployment (timeout ~50 mins)
  k8s:
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
    state: present
    wait: true
    wait_timeout: 2400
    wait_condition:
      type: Complete
      status: "True"
      reason: ComponentsAvailable
  register: mch_deployment
  retries: 10
  delay: 30
  until: mch_deployment is not failed
  ignore_errors: True
